version: '3'

networks:
  app-tier:
    driver: bridge

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app-tier
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
    ports:
      - '9092:9092'
    networks:
      - app-tier
  producer:
    container_name: producer
    build: ./Producer
    networks:
      - app-tier
    ports:
      - "8000:8000"
    depends_on:
      - kafka
      - zookeeper
  consumer:
    container_name: consumer
    build: ./Consumer
    networks:
      - app-tier
    ports:
      - "5000:5000"
    depends_on:
      - kafka
      - zookeeper
      - producer